"""
mongo_db.py — Async MongoDB client for the Silver Challenge live-chat feature.

Uses the Motor async driver so it integrates cleanly with FastAPI's event loop.
Database : subsync
Collection: messages

Message document shape:
  {
      "_id":             ObjectId  (auto-generated by MongoDB),
      "sender_username": str,
      "text":            str,
      "timestamp":       str  (ISO 8601, e.g. "2026-05-20T18:00:00.000000")
  }
"""

from datetime import datetime, timezone
import motor.motor_asyncio

MONGO_URL = "mongodb://localhost:27017"
DB_NAME   = "subsync"
COL_NAME  = "messages"

# Single shared client — Motor handles the connection pool internally.
client     = motor.motor_asyncio.AsyncIOMotorClient(MONGO_URL)
db         = client[DB_NAME]
collection = db[COL_NAME]


async def insert_message(sender_username: str, text: str) -> dict:
    """Persist a new chat message and return it as a plain dict."""
    doc = {
        "sender_username": sender_username,
        "text":            text,
        "timestamp":       datetime.now(timezone.utc).isoformat(),
    }
    result = await collection.insert_one(doc)
    doc["_id"] = str(result.inserted_id)   # make ObjectId JSON-serialisable
    return doc


async def get_recent_messages(limit: int = 50) -> list[dict]:
    """Return the last *limit* messages in chronological order (oldest first)."""
    cursor = collection.find().sort("timestamp", 1).limit(limit)
    messages = []
    async for doc in cursor:
        doc["_id"] = str(doc["_id"])        # make ObjectId JSON-serialisable
        messages.append(doc)
    return messages
